/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package BPMN20.validation;

import BPMN20.AdHocOrdering;
import BPMN20.Expression;

/**
 * A sample validator interface for {@link BPMN20.AdHocSubProcess}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AdHocSubProcessValidator {
	boolean validate();

	boolean validateCompletionCondition(Expression value);
	boolean validateOrdering(AdHocOrdering value);
	boolean validateCancelRemainingInstances(boolean value);
}
