/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package BPMN20.validation;

import BPMN20.AssociationDirection;
import BPMN20.BaseElement;

/**
 * A sample validator interface for {@link BPMN20.Association}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AssociationValidator {
	boolean validate();

	boolean validateAssociationDirection(AssociationDirection value);
	boolean validateSourceRef(BaseElement value);
	boolean validateTargetRef(BaseElement value);
}
