/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package BPMN20.validation;

import BPMN20.Documentation;
import BPMN20.ExtensionAttributeValue;
import BPMN20.ExtensionDefinition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link BPMN20.BaseElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BaseElementValidator {
	boolean validate();

	boolean validateId(Object value);
	boolean validateExtensionDefinitions(EList<ExtensionDefinition> value);
	boolean validateExtensionValues(EList<ExtensionAttributeValue> value);
	boolean validateDocumentation(EList<Documentation> value);
}
