/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package BPMN20.validation;

import BPMN20.Artifact;
import BPMN20.Choreography;
import BPMN20.ConversationAssociation;
import BPMN20.ConversationLink;
import BPMN20.ConversationNode;
import BPMN20.CorrelationKey;
import BPMN20.MessageFlow;
import BPMN20.MessageFlowAssociation;
import BPMN20.Participant;
import BPMN20.ParticipantAssociation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link BPMN20.Collaboration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CollaborationValidator {
	boolean validate();

	boolean validateName(Object value);
	boolean validateIsClosed(Object value);
	boolean validateChoreographyRef(EList<Choreography> value);
	boolean validateArtifacts(EList<Artifact> value);
	boolean validateParticipantAssociations(EList<ParticipantAssociation> value);
	boolean validateMessageFlowAssociations(EList<MessageFlowAssociation> value);
	boolean validateConversationAssociations(ConversationAssociation value);
	boolean validateParticipants(EList<Participant> value);
	boolean validateMessageFlows(EList<MessageFlow> value);
	boolean validateCorrelationKeys(EList<CorrelationKey> value);
	boolean validateConversations(EList<ConversationNode> value);
	boolean validateConversationLinks(EList<ConversationLink> value);
}
