/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package BPMN20.validation;

import BPMN20.Expression;
import BPMN20.SequenceFlow;

/**
 * A sample validator interface for {@link BPMN20.ComplexGateway}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComplexGatewayValidator {
	boolean validate();

	boolean validateActivationCondition(Expression value);
	boolean validateDefault(SequenceFlow value);
}
