/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package BPMN20.validation;

import BPMN20.CorrelationKey;
import BPMN20.CorrelationPropertyBinding;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link BPMN20.CorrelationSubscription}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CorrelationSubscriptionValidator {
	boolean validate();

	boolean validateCorrelationKeyRef(CorrelationKey value);
	boolean validateCorrelationPropertyBinding(EList<CorrelationPropertyBinding> value);
}
