/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package BPMN20.validation;

import BPMN20.CorrelationProperty;
import BPMN20.FormalExpression;

/**
 * A sample validator interface for {@link BPMN20.CorrelationPropertyBinding}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CorrelationPropertyBindingValidator {
	boolean validate();

	boolean validateDataPath(FormalExpression value);
	boolean validateCorrelationPropertyRef(CorrelationProperty value);
}
