/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package BPMN20.validation;


/**
 * A sample validator interface for {@link BPMN20.DataStore}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataStoreValidator {
	boolean validate();

	boolean validateName(Object value);
	boolean validateCapacity(Object value);
	boolean validateIsUnlimited(boolean value);
}
