/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package BPMN20.validation;

import BPMN20.Extension;
import BPMN20.Import;
import BPMN20.Relationship;
import BPMN20.RootElement;

import BPMNDI.BPMNDiagram;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link BPMN20.Definitions}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DefinitionsValidator {
	boolean validate();

	boolean validateName(Object value);
	boolean validateTargetNamespace(Object value);
	boolean validateExpressionLanguage(String value);
	boolean validateTypeLanguage(String value);
	boolean validateImports(EList<Import> value);
	boolean validateExtensions(EList<Extension> value);
	boolean validateRelationships(EList<Relationship> value);
	boolean validateRootElements(EList<RootElement> value);
	boolean validateDiagrams(EList<BPMNDiagram> value);
	boolean validateExporter(Object value);
	boolean validateExporterVersion(Object value);
}
