/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package BPMN20.validation;

import BPMN20.ItemDefinition;

import org.eclipse.emf.ecore.EObject;

/**
 * A sample validator interface for {@link BPMN20.FormalExpression}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FormalExpressionValidator {
	boolean validate();

	boolean validateLanguage(Object value);
	boolean validateBody(EObject value);
	boolean validateEvaluatesToTypeRef(ItemDefinition value);
}
