/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package BPMN20.validation;

import BPMN20.DataInput;
import BPMN20.OutputSet;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link BPMN20.InputSet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InputSetValidator {
	boolean validate();

	boolean validateName(Object value);
	boolean validateDataInputRefs(EList<DataInput> value);
	boolean validateOptionalInputRefs(EList<DataInput> value);
	boolean validateWhileExecutingInputRefs(EList<DataInput> value);
	boolean validateOutputSetRefs(EList<OutputSet> value);
}
