/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package BPMN20.validation;

import BPMN20.DataInput;
import BPMN20.DataOutput;
import BPMN20.InputSet;
import BPMN20.OutputSet;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link BPMN20.InputOutputSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InputOutputSpecificationValidator {
	boolean validate();

	boolean validateInputSets(EList<InputSet> value);
	boolean validateOutputSets(EList<OutputSet> value);
	boolean validateDataInputs(EList<DataInput> value);
	boolean validateDataOutputs(EList<DataOutput> value);
}
