/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package BPMN20.validation;

import BPMN20.Artifact;
import BPMN20.Auditing;
import BPMN20.Collaboration;
import BPMN20.CorrelationSubscription;
import BPMN20.Monitoring;
import BPMN20.ProcessType;
import BPMN20.Property;
import BPMN20.ResourceRole;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link BPMN20.Process}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProcessValidator {
	boolean validate();

	boolean validateProcessType(ProcessType value);
	boolean validateIsClosed(Object value);
	boolean validateAuditing(Auditing value);
	boolean validateMonitoring(Monitoring value);
	boolean validateProperties(EList<Property> value);
	boolean validateSupports(EList<BPMN20.Process> value);
	boolean validateDefinitionalCollaborationRef(Collaboration value);
	boolean validateIsExecutable(Object value);
	boolean validateResources(EList<ResourceRole> value);
	boolean validateArtifacts(EList<Artifact> value);
	boolean validateCorrelationSubscriptions(EList<CorrelationSubscription> value);
}
