/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package DC.validation;


/**
 * A sample validator interface for {@link DC.Bounds}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BoundsValidator {
	boolean validate();

	boolean validateX(Object value);
	boolean validateY(Object value);
	boolean validateWidth(Object value);
	boolean validateHeight(Object value);
}
