/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package DC.validation;


/**
 * A sample validator interface for {@link DC.Font}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FontValidator {
	boolean validate();

	boolean validateName(Object value);
	boolean validateSize(Object value);
	boolean validateIsBold(Object value);
	boolean validateIsItalic(Object value);
	boolean validateIsUnderline(Object value);
	boolean validateIsStrikeThrough(Object value);
}
