/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package BPMNDI.validation;

import BPMN20.BaseElement;

import BPMNDI.BPMNLabel;
import BPMNDI.BPMNShape;
import BPMNDI.ParticipantBandKind;

/**
 * A sample validator interface for {@link BPMNDI.BPMNShape}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BPMNShapeValidator {
	boolean validate();

	boolean validateBpmnElement(BaseElement value);
	boolean validateIsHorizontal(Object value);
	boolean validateIsExpanded(Object value);
	boolean validateIsMarkerVisible(Object value);
	boolean validateLabel(BPMNLabel value);
	boolean validateIsMessageVisible(Object value);
	boolean validateParticipantBandKind(ParticipantBandKind value);
	boolean validateChoreographyActivityShape(BPMNShape value);
}
